"""End-to-end smoke test for monday_rotocon v0.2.1.

Reads the "KI Integration" board via the library, builds an
Obsidian-flavored Markdown report + an HTML email (with a QuickChart
bar chart), saves the Markdown locally to `reports/`, and POSTs to an
n8n webhook that fans out via M365 Outlook.

Unlike `bootstrap_ki_integration.py`, this script DOES import
`monday_rotocon` — that's the whole point. Run it with `uv run`
so the venv is active:

    uv run python scripts/smoke_ki_integration_report.py [--dry-run]

The script never mutates monday state; the read-only invariant of
the library still holds.
"""

from __future__ import annotations

import argparse
import os
import sys
from collections import OrderedDict
from dataclasses import dataclass
from datetime import datetime

from monday_rotocon import Item


@dataclass(frozen=True)
class RequiredEnv:
    monday_token: str
    webhook_url: str
    webhook_token: str
    recipient: str


def load_env() -> RequiredEnv:
    """Read required env vars. Exits the process with code 1 if any are missing."""
    required = {
        "MONDAY_API_TOKEN": "monday_token",
        "N8N_WEBHOOK_URL": "webhook_url",
        "N8N_WEBHOOK_TOKEN": "webhook_token",
        "REPORT_RECIPIENT": "recipient",
    }
    values: dict[str, str] = {}
    missing: list[str] = []
    for env_name, attr_name in required.items():
        v = os.environ.get(env_name, "").strip()
        if not v:
            missing.append(env_name)
        else:
            values[attr_name] = v
    if missing:
        print(f"Missing required env: {', '.join(missing)}", file=sys.stderr)
        raise SystemExit(1)
    return RequiredEnv(**values)


def group_items_by_title(items: list[Item]) -> list[tuple[str, int]]:
    """Count items per group title, preserving first-seen order.

    Items without a group are bucketed under "(ungrouped)".
    """
    counts: OrderedDict[str, int] = OrderedDict()
    for item in items:
        title = item.group.title if item.group is not None else "(ungrouped)"
        counts[title] = counts.get(title, 0) + 1
    return list(counts.items())


@dataclass(frozen=True)
class ReportData:
    board_id: str
    board_name: str
    workspace_id: str
    generated_at: datetime
    client_version: str
    run_id: str
    group_counts: list[tuple[str, int]]
    total_items: int


def _percent(part: int, total: int) -> str:
    if total == 0:
        return "0%"
    return f"{round(100 * part / total)}%"


def render_markdown(report: ReportData) -> str:
    ts = report.generated_at.strftime("%Y-%m-%d %H:%M UTC")
    date_only = report.generated_at.strftime("%Y-%m-%d")

    frontmatter = (
        "---\n"
        f"title: {report.board_name} — Smoke Test Report\n"
        f"date: {date_only}\n"
        f"client: {report.client_version}\n"
        f"board_id: {report.board_id}\n"
        "tags: [smoke-test, monday, ki-integration]\n"
        "---\n\n"
    )

    callout = (
        "> [!info] Smoke Test Run\n"
        f"> **Board:** {report.board_name} (`{report.board_id}`)\n"
        f"> **Workspace:** ROTOCON EU SERVICE (`{report.workspace_id}`)\n"
        f"> **Generated:** {ts}\n"
        f"> **Total items:** {report.total_items} — peste "
        f"{len(report.group_counts)} grupuri\n"
        f"> **Transport:** `{report.client_version}`\n\n"
    )

    pie_lines = [f'    "{title}" : {count}' for title, count in report.group_counts]
    mermaid = (
        "## Distribuție itemi per grup\n\n"
        "```mermaid\n"
        "pie title Itemi per grup\n"
        + "\n".join(pie_lines)
        + "\n```\n\n"
    )

    table_rows = [
        f"| {title} | {count} | {_percent(count, report.total_items)} |"
        for title, count in report.group_counts
    ]
    table = (
        "| Grup | Itemi | % din total |\n"
        "|---|---:|---:|\n"
        + "\n".join(table_rows)
        + f"\n| **Total** | **{report.total_items}** | **100%** |\n\n"
    )

    checklist = (
        "## Verificări end-to-end\n\n"
        "- [x] `MondayClient.boards()` — board găsit după nume\n"
        "- [x] `MondayClient.items_for_board()` — paginare cursor completă\n"
        "- [x] Parsare Pydantic (`extra=\"ignore\"`)\n"
        "- [x] Webhook n8n acceptat (HTTP 200)\n"
        "- [x] M365 Outlook — email livrat\n\n"
    )

    footer = (
        "---\n"
        f"*Generated by `scripts/smoke_ki_integration_report.py` · "
        f"run id `{report.run_id}`*\n"
    )

    return frontmatter + callout + mermaid + table + checklist + footer


def main() -> int:
    parser = argparse.ArgumentParser(description="KI Integration smoke report")
    parser.add_argument("--dry-run", action="store_true",
                        help="Fetch + render + save Markdown locally; do not POST to n8n.")
    args = parser.parse_args()
    _ = load_env()
    # The rest of main() is implemented in Task 10.
    raise SystemExit(0 if args.dry_run else 0)


if __name__ == "__main__":
    raise SystemExit(main())
