"""End-to-end smoke test for monday_rotocon v0.2.1.

Reads the "KI Integration" board via the library, builds an
Obsidian-flavored Markdown report + an HTML email (with a QuickChart
bar chart), saves the Markdown locally to `reports/`, and POSTs to an
n8n webhook that fans out via M365 Outlook.

Unlike `bootstrap_ki_integration.py`, this script DOES import
`monday_rotocon` — that's the whole point. Run it with `uv run`
so the venv is active:

    uv run python scripts/smoke_ki_integration_report.py [--dry-run]

The script never mutates monday state; the read-only invariant of
the library still holds.
"""

from __future__ import annotations

import argparse
import base64
import json
import os
import sys
import time
import uuid
from collections import OrderedDict
from dataclasses import dataclass
from datetime import UTC, datetime
from html import escape
from pathlib import Path
from typing import TypedDict
from urllib.parse import quote

import httpx

from monday_rotocon import Board, Item, MondayAPIError, MondayClient

Q_FIND_BOARDS = """
query FindBoards($workspace_ids: [ID!]!) {
  boards(workspace_ids: $workspace_ids, limit: 200, state: active) {
    id
    name
    workspace_id
  }
}
""".strip()

DEFAULT_WORKSPACE_ID = "5528271"
DEFAULT_BOARD_NAME = "KI Integration"


@dataclass(frozen=True)
class RequiredEnv:
    monday_token: str
    webhook_url: str
    webhook_token: str
    recipient: str


def load_env() -> RequiredEnv:
    """Read required env vars. Exits the process with code 1 if any are missing."""
    required = {
        "MONDAY_API_TOKEN": "monday_token",
        "N8N_WEBHOOK_URL": "webhook_url",
        "N8N_WEBHOOK_TOKEN": "webhook_token",
        "REPORT_RECIPIENT": "recipient",
    }
    values: dict[str, str] = {}
    missing: list[str] = []
    for env_name, attr_name in required.items():
        v = os.environ.get(env_name, "").strip()
        if not v:
            missing.append(env_name)
        else:
            values[attr_name] = v
    if missing:
        print(f"Missing required env: {', '.join(missing)}", file=sys.stderr)
        raise SystemExit(1)
    return RequiredEnv(**values)


def group_items_by_title(items: list[Item]) -> list[tuple[str, int]]:
    """Count items per group title, preserving first-seen order.

    Items without a group are bucketed under "(ungrouped)".
    """
    counts: OrderedDict[str, int] = OrderedDict()
    for item in items:
        title = item.group.title if item.group is not None else "(ungrouped)"
        counts[title] = counts.get(title, 0) + 1
    return list(counts.items())


@dataclass(frozen=True)
class ReportData:
    board_id: str
    board_name: str
    workspace_id: str
    generated_at: datetime
    client_version: str
    run_id: str
    group_counts: list[tuple[str, int]]
    total_items: int


def _percent(part: int, total: int) -> str:
    if total == 0:
        return "0%"
    return f"{round(100 * part / total)}%"


def render_markdown(report: ReportData) -> str:
    ts = report.generated_at.strftime("%Y-%m-%d %H:%M UTC")
    date_only = report.generated_at.strftime("%Y-%m-%d")

    frontmatter = (
        "---\n"
        f"title: {report.board_name} — Smoke Test Report\n"
        f"date: {date_only}\n"
        f"client: {report.client_version}\n"
        f"board_id: {report.board_id}\n"
        "tags: [smoke-test, monday, ki-integration]\n"
        "---\n\n"
    )

    callout = (
        "> [!info] Smoke Test Run\n"
        f"> **Board:** {report.board_name} (`{report.board_id}`)\n"
        f"> **Workspace:** ROTOCON EU SERVICE (`{report.workspace_id}`)\n"
        f"> **Generated:** {ts}\n"
        f"> **Total items:** {report.total_items} — peste "
        f"{len(report.group_counts)} grupuri\n"
        f"> **Transport:** `{report.client_version}`\n\n"
    )

    pie_lines = [f'    "{title}" : {count}' for title, count in report.group_counts]
    mermaid = (
        "## Distribuție itemi per grup\n\n"
        "```mermaid\n"
        "pie title Itemi per grup\n" + "\n".join(pie_lines) + "\n```\n\n"
    )

    table_rows = [
        f"| {title} | {count} | {_percent(count, report.total_items)} |"
        for title, count in report.group_counts
    ]
    table = (
        "| Grup | Itemi | % din total |\n"
        "|---|---:|---:|\n"
        + "\n".join(table_rows)
        + f"\n| **Total** | **{report.total_items}** | **100%** |\n\n"
    )

    checklist = (
        "## Verificări end-to-end\n\n"
        "- [x] `MondayClient.boards()` — board găsit după nume\n"
        "- [x] `MondayClient.items_for_board()` — paginare cursor completă\n"
        '- [x] Parsare Pydantic (`extra="ignore"`)\n'
        "- [x] Webhook n8n acceptat (HTTP 200)\n"
        "- [x] M365 Outlook — email livrat\n\n"
    )

    footer = (
        f"---\n*Generated by `scripts/smoke_ki_integration_report.py` · run id `{report.run_id}`*\n"
    )

    return frontmatter + callout + mermaid + table + checklist + footer


def quickchart_url(
    group_counts: list[tuple[str, int]], *, width: int = 600, height: int = 300
) -> str:
    """Build a QuickChart.io URL rendering a horizontal bar chart."""
    config = {
        "type": "horizontalBar",
        "data": {
            "labels": [title for title, _ in group_counts],
            "datasets": [
                {
                    "data": [count for _, count in group_counts],
                    "backgroundColor": "#2563eb",
                }
            ],
        },
        "options": {
            "legend": {"display": False},
            "title": {"display": True, "text": "Itemi per grup"},
        },
    }
    return (
        "https://quickchart.io/chart"
        f"?w={width}&h={height}&c={quote(json.dumps(config, separators=(',', ':')))}"
    )


def render_html(report: ReportData, *, recipient: str) -> str:
    ts = report.generated_at.strftime("%Y-%m-%d %H:%M UTC")
    chart_src = quickchart_url(report.group_counts)
    rows_html = "".join(
        f"<tr><td>{escape(title)}</td><td style='text-align:right'>{count}</td></tr>"
        for title, count in report.group_counts
    )
    return f"""\
<!doctype html>
<html lang="ro">
<head><meta charset="utf-8"><title>{escape(report.board_name)} — Smoke Test Report</title></head>
<body style="font-family: -apple-system, Segoe UI, Helvetica, Arial, sans-serif; color:#111; max-width:680px; margin:0 auto; padding:24px;">
  <header style="background:#f4f4f5; padding:16px 20px; border-radius:8px; margin-bottom:20px;">
    <h1 style="margin:0 0 6px 0; font-size:20px;">{escape(report.board_name)} — Smoke Test Report</h1>
    <div style="color:#52525b; font-size:13px;">
      Board <code>{escape(report.board_id)}</code> · Generated {ts} · {escape(report.client_version)}
    </div>
  </header>

  <h2 style="font-size:16px; margin:24px 0 8px 0;">Itemi per grup</h2>
  <table cellpadding="6" cellspacing="0" border="0"
         style="border-collapse:collapse; width:100%; border:1px solid #e4e4e7; font-size:14px;">
    <thead style="background:#fafafa;">
      <tr><th style="text-align:left">Grup</th><th style="text-align:right">Itemi</th></tr>
    </thead>
    <tbody>
      {rows_html}
      <tr style="border-top:2px solid #e4e4e7; background:#fafafa;">
        <td><strong>Total</strong></td>
        <td style="text-align:right"><strong>{report.total_items}</strong></td>
      </tr>
    </tbody>
  </table>

  <div style="margin-top:24px;">
    <img src="{chart_src}" alt="Itemi per grup — bar chart"
         width="600" height="300" style="max-width:100%; height:auto; border:1px solid #e4e4e7; border-radius:6px;">
  </div>

  <footer style="margin-top:32px; padding-top:12px; border-top:1px solid #e4e4e7; color:#71717a; font-size:12px;">
    Smoke test rulat de {escape(report.client_version)} · run id <code>{escape(report.run_id)}</code><br>
    Destinatar: {escape(recipient)}
  </footer>
</body>
</html>
"""


class MarkdownAttachment(TypedDict):
    filename: str
    content_base64: str
    mime_type: str


class WebhookPayload(TypedDict):
    subject: str
    recipient: str
    html_body: str
    markdown_attachment: MarkdownAttachment


def build_payload(
    *,
    report: ReportData,
    recipient: str,
    markdown: str,
    html_body: str,
    markdown_filename: str,
) -> WebhookPayload:
    date_only = report.generated_at.strftime("%Y-%m-%d")
    return WebhookPayload(
        subject=f"{report.board_name} smoke test — {date_only}",
        recipient=recipient,
        html_body=html_body,
        markdown_attachment=MarkdownAttachment(
            filename=markdown_filename,
            content_base64=base64.b64encode(markdown.encode("utf-8")).decode("ascii"),
            mime_type="text/markdown",
        ),
    )


class N8nWebhookError(RuntimeError):
    """Raised when the n8n webhook fails after all retries."""


def _sleep(seconds: float) -> None:
    time.sleep(seconds)  # pragma: no cover — wrapper; monkeypatched in tests


def post_to_n8n(
    *,
    url: str,
    token: str,
    payload: WebhookPayload | dict,
    timeout: float = 30.0,
    max_attempts: int = 3,
) -> dict:
    """POST `payload` to the n8n webhook with header auth and bounded retry.

    Retries `max_attempts` times on `httpx.TransportError` with exponential
    backoff (1s, 2s, ...). A non-2xx response raises immediately without retry.
    """
    last_exc: Exception | None = None
    for attempt in range(max_attempts):
        try:
            response = httpx.post(
                url,
                json=payload,
                headers={"X-Smoke-Token": token, "Content-Type": "application/json"},
                timeout=timeout,
            )
        except httpx.TransportError as exc:
            last_exc = exc
            if attempt < max_attempts - 1:
                _sleep(1.0 * (2**attempt))
                continue
            raise N8nWebhookError(
                f"transport error after {max_attempts} attempts: {exc!r}"
            ) from exc

        if response.status_code // 100 != 2:
            raise N8nWebhookError(
                f"n8n webhook returned {response.status_code}: {response.text[:500]}"
            )
        try:
            return response.json()
        except ValueError:
            return {"status": "ok", "raw": response.text[:500]}
    # Defensive: loop should always either return or raise.
    raise N8nWebhookError(f"unreachable; last exc: {last_exc!r}")  # pragma: no cover


class BoardNotFoundError(RuntimeError):
    """Raised when the target board doesn't exist in the workspace."""


def find_board_by_name(client: MondayClient, *, name: str, workspace_id: str) -> Board:
    """Look up a board by exact name within a workspace.

    Raises BoardNotFoundError with a list of board names as a hint if no
    match. Uses an ad-hoc query (not in the library) because the library's
    `boards()` is ID-based; this is the workspace-scoped variant the
    smoke test needs.
    """
    data = client.execute(Q_FIND_BOARDS, variables={"workspace_ids": [workspace_id]})
    boards = data.get("boards") or []
    matches = [b for b in boards if b.get("name") == name]
    if not matches:
        seen = ", ".join(sorted({b.get("name", "?") for b in boards})) or "<none>"
        raise BoardNotFoundError(
            f"Board {name!r} not found in workspace {workspace_id}. Boards seen: {seen}"
        )
    return Board.model_validate(matches[0])


def _now_utc() -> datetime:
    return datetime.now(tz=UTC)


def main() -> int:
    parser = argparse.ArgumentParser(description="KI Integration smoke report")
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Fetch + render + save Markdown locally; do not POST to n8n.",
    )
    parser.add_argument(
        "--workspace-id",
        default=DEFAULT_WORKSPACE_ID,
        help=f"Workspace ID (default: {DEFAULT_WORKSPACE_ID})",
    )
    parser.add_argument(
        "--board-name",
        default=DEFAULT_BOARD_NAME,
        help=f"Board name (default: {DEFAULT_BOARD_NAME!r})",
    )
    args = parser.parse_args()
    env = load_env()

    from monday_rotocon import __version__

    try:
        with MondayClient(api_token=env.monday_token) as client:
            board = find_board_by_name(client, name=args.board_name, workspace_id=args.workspace_id)
            items = list(client.items_for_board(board_id=board.id))
    except BoardNotFoundError as exc:
        print(str(exc), file=sys.stderr)
        return 4
    except MondayAPIError as exc:
        print(f"monday API error: {exc!r}", file=sys.stderr)
        return 2

    group_counts = group_items_by_title(items)
    generated_at = _now_utc()
    run_id = uuid.uuid4().hex[:16]
    report = ReportData(
        board_id=str(board.id),
        board_name=board.name,
        workspace_id=args.workspace_id,
        generated_at=generated_at,
        client_version=f"monday_rotocon v{__version__}",
        run_id=run_id,
        group_counts=group_counts,
        total_items=len(items),
    )

    md = render_markdown(report)
    html = render_html(report, recipient=env.recipient)

    reports_dir = Path("reports")
    reports_dir.mkdir(exist_ok=True)
    stamp = generated_at.strftime("%Y-%m-%d-%H%M")
    md_filename = f"{stamp}-ki-integration-smoke.md"
    md_path = reports_dir / md_filename
    md_path.write_text(md, encoding="utf-8")
    print(f"Wrote {md_path}")

    if args.dry_run:
        print(f"--dry-run: skipping n8n POST (board_id={board.id}, items={len(items)})")
        return 0

    payload = build_payload(
        report=report,
        recipient=env.recipient,
        markdown=md,
        html_body=html,
        markdown_filename=md_filename,
    )
    try:
        response = post_to_n8n(url=env.webhook_url, token=env.webhook_token, payload=payload)
    except N8nWebhookError as exc:
        print(f"n8n webhook error: {exc!r}", file=sys.stderr)
        return 3

    print(
        f"OK board_id={board.id} items={len(items)} "
        f"n8n_messageId={response.get('messageId', '?')} markdown={md_path}"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
