"""End-to-end smoke test for monday_rotocon v0.2.1.

Reads the "KI Integration" board via the library, builds an
Obsidian-flavored Markdown report + an HTML email (with a QuickChart
bar chart), saves the Markdown locally to `reports/`, and POSTs to an
n8n webhook that fans out via M365 Outlook.

Unlike `bootstrap_ki_integration.py`, this script DOES import
`monday_rotocon` — that's the whole point. Run it with `uv run`
so the venv is active:

    uv run python scripts/smoke_ki_integration_report.py [--dry-run]

The script never mutates monday state; the read-only invariant of
the library still holds.
"""

from __future__ import annotations

import argparse
import json
import os
import sys
from collections import OrderedDict
from dataclasses import dataclass
from datetime import datetime
from html import escape
from urllib.parse import quote

from monday_rotocon import Item


@dataclass(frozen=True)
class RequiredEnv:
    monday_token: str
    webhook_url: str
    webhook_token: str
    recipient: str


def load_env() -> RequiredEnv:
    """Read required env vars. Exits the process with code 1 if any are missing."""
    required = {
        "MONDAY_API_TOKEN": "monday_token",
        "N8N_WEBHOOK_URL": "webhook_url",
        "N8N_WEBHOOK_TOKEN": "webhook_token",
        "REPORT_RECIPIENT": "recipient",
    }
    values: dict[str, str] = {}
    missing: list[str] = []
    for env_name, attr_name in required.items():
        v = os.environ.get(env_name, "").strip()
        if not v:
            missing.append(env_name)
        else:
            values[attr_name] = v
    if missing:
        print(f"Missing required env: {', '.join(missing)}", file=sys.stderr)
        raise SystemExit(1)
    return RequiredEnv(**values)


def group_items_by_title(items: list[Item]) -> list[tuple[str, int]]:
    """Count items per group title, preserving first-seen order.

    Items without a group are bucketed under "(ungrouped)".
    """
    counts: OrderedDict[str, int] = OrderedDict()
    for item in items:
        title = item.group.title if item.group is not None else "(ungrouped)"
        counts[title] = counts.get(title, 0) + 1
    return list(counts.items())


@dataclass(frozen=True)
class ReportData:
    board_id: str
    board_name: str
    workspace_id: str
    generated_at: datetime
    client_version: str
    run_id: str
    group_counts: list[tuple[str, int]]
    total_items: int


def _percent(part: int, total: int) -> str:
    if total == 0:
        return "0%"
    return f"{round(100 * part / total)}%"


def render_markdown(report: ReportData) -> str:
    ts = report.generated_at.strftime("%Y-%m-%d %H:%M UTC")
    date_only = report.generated_at.strftime("%Y-%m-%d")

    frontmatter = (
        "---\n"
        f"title: {report.board_name} — Smoke Test Report\n"
        f"date: {date_only}\n"
        f"client: {report.client_version}\n"
        f"board_id: {report.board_id}\n"
        "tags: [smoke-test, monday, ki-integration]\n"
        "---\n\n"
    )

    callout = (
        "> [!info] Smoke Test Run\n"
        f"> **Board:** {report.board_name} (`{report.board_id}`)\n"
        f"> **Workspace:** ROTOCON EU SERVICE (`{report.workspace_id}`)\n"
        f"> **Generated:** {ts}\n"
        f"> **Total items:** {report.total_items} — peste "
        f"{len(report.group_counts)} grupuri\n"
        f"> **Transport:** `{report.client_version}`\n\n"
    )

    pie_lines = [f'    "{title}" : {count}' for title, count in report.group_counts]
    mermaid = (
        "## Distribuție itemi per grup\n\n"
        "```mermaid\n"
        "pie title Itemi per grup\n"
        + "\n".join(pie_lines)
        + "\n```\n\n"
    )

    table_rows = [
        f"| {title} | {count} | {_percent(count, report.total_items)} |"
        for title, count in report.group_counts
    ]
    table = (
        "| Grup | Itemi | % din total |\n"
        "|---|---:|---:|\n"
        + "\n".join(table_rows)
        + f"\n| **Total** | **{report.total_items}** | **100%** |\n\n"
    )

    checklist = (
        "## Verificări end-to-end\n\n"
        "- [x] `MondayClient.boards()` — board găsit după nume\n"
        "- [x] `MondayClient.items_for_board()` — paginare cursor completă\n"
        "- [x] Parsare Pydantic (`extra=\"ignore\"`)\n"
        "- [x] Webhook n8n acceptat (HTTP 200)\n"
        "- [x] M365 Outlook — email livrat\n\n"
    )

    footer = (
        "---\n"
        f"*Generated by `scripts/smoke_ki_integration_report.py` · "
        f"run id `{report.run_id}`*\n"
    )

    return frontmatter + callout + mermaid + table + checklist + footer


def quickchart_url(group_counts: list[tuple[str, int]], *, width: int = 600,
                   height: int = 300) -> str:
    """Build a QuickChart.io URL rendering a horizontal bar chart."""
    config = {
        "type": "horizontalBar",
        "data": {
            "labels": [title for title, _ in group_counts],
            "datasets": [
                {
                    "data": [count for _, count in group_counts],
                    "backgroundColor": "#2563eb",
                }
            ],
        },
        "options": {
            "legend": {"display": False},
            "title": {"display": True, "text": "Itemi per grup"},
        },
    }
    return (
        "https://quickchart.io/chart"
        f"?w={width}&h={height}&c={quote(json.dumps(config, separators=(',', ':')))}"
    )


def render_html(report: ReportData, *, recipient: str) -> str:
    ts = report.generated_at.strftime("%Y-%m-%d %H:%M UTC")
    chart_src = quickchart_url(report.group_counts)
    rows_html = "".join(
        f"<tr><td>{escape(title)}</td>"
        f"<td style='text-align:right'>{count}</td></tr>"
        for title, count in report.group_counts
    )
    return f"""\
<!doctype html>
<html lang="ro">
<head><meta charset="utf-8"><title>{escape(report.board_name)} — Smoke Test Report</title></head>
<body style="font-family: -apple-system, Segoe UI, Helvetica, Arial, sans-serif; color:#111; max-width:680px; margin:0 auto; padding:24px;">
  <header style="background:#f4f4f5; padding:16px 20px; border-radius:8px; margin-bottom:20px;">
    <h1 style="margin:0 0 6px 0; font-size:20px;">{escape(report.board_name)} — Smoke Test Report</h1>
    <div style="color:#52525b; font-size:13px;">
      Board <code>{escape(report.board_id)}</code> · Generated {ts} · {escape(report.client_version)}
    </div>
  </header>

  <h2 style="font-size:16px; margin:24px 0 8px 0;">Itemi per grup</h2>
  <table cellpadding="6" cellspacing="0" border="0"
         style="border-collapse:collapse; width:100%; border:1px solid #e4e4e7; font-size:14px;">
    <thead style="background:#fafafa;">
      <tr><th style="text-align:left">Grup</th><th style="text-align:right">Itemi</th></tr>
    </thead>
    <tbody>
      {rows_html}
      <tr style="border-top:2px solid #e4e4e7; background:#fafafa;">
        <td><strong>Total</strong></td>
        <td style="text-align:right"><strong>{report.total_items}</strong></td>
      </tr>
    </tbody>
  </table>

  <div style="margin-top:24px;">
    <img src="{chart_src}" alt="Itemi per grup — bar chart"
         width="600" height="300" style="max-width:100%; height:auto; border:1px solid #e4e4e7; border-radius:6px;">
  </div>

  <footer style="margin-top:32px; padding-top:12px; border-top:1px solid #e4e4e7; color:#71717a; font-size:12px;">
    Smoke test rulat de {escape(report.client_version)} · run id <code>{escape(report.run_id)}</code><br>
    Destinatar: {escape(recipient)}
  </footer>
</body>
</html>
"""


def main() -> int:
    parser = argparse.ArgumentParser(description="KI Integration smoke report")
    parser.add_argument("--dry-run", action="store_true",
                        help="Fetch + render + save Markdown locally; do not POST to n8n.")
    args = parser.parse_args()
    _ = load_env()
    # The rest of main() is implemented in Task 10.
    raise SystemExit(0 if args.dry_run else 0)


if __name__ == "__main__":
    raise SystemExit(main())
